baseURL = "https://startupandrew.com/"
languageCode = "en-us"
title = "Andrew's Blog"
theme = "hyde-hyde"

## Site Settings
[params]
    author = "Andrew Lee"
    description = "This is a description."
    authorimage = "/images/andrew.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    themeColor = "theme-base-0c"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "startupandrew"
    linkedin = "startupandrew"
    twitter = "startupandrew"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"